Repository Caltech-IPAC/irsa-tutorials, pull requests merged in 2024-09, with the labels that each got.

#29 CI: fail rendering job on errors
  conf.py
  tox.ini
Labels: infrastructure, html rendering

#31 ENH: merge streams for nicer looking outputs
  conf.py
Labels: html rendering

#30 DOC: adding more links to the index page
  index.md
Labels: html rendering

#32 CI: adding monthly dependabot
  .github/dependabot.yml
Labels: infrastructure, html rendering

#33 CI: add optin to build html on GHA
  .github/workflows/ci_tests_run_notebooks.yml
Labels: html rendering, GHA buildhtml

#16 Add notebooks for NEOWISE parquet catalog
  conf.py
  ignore_gha_testing
  index.md
  tox.ini
  tutorials/parquet-catalog-demos/neowise-source-table-lightcurves.md
  tutorials/parquet-catalog-demos/neowise-source-table-strategies.md
  tutorials/requirements.txt
Labels: content, GHA buildhtml

#35 DOC: making pip install cells consistent
  tutorials/cloud_access/cloud-access-intro.md
  tutorials/cosmodc2/cosmoDC2_TAP_access.md
  tutorials/firefly/NEOWISE_light_curve_demo.md
  tutorials/firefly/SEDs_in_Firefly.md
  tutorials/irsa-sia-examples/sia_2mass_allsky.md
  tutorials/irsa-sia-examples/sia_allwise_atlas.md
  tutorials/irsa-sia-examples/sia_cosmos.md
  tutorials/irsa-sia-examples/siav2_seip.md
  tutorials/openuniversesims/openuniverse2024_roman_simulated_timedomainsurvey.md
  tutorials/openuniversesims/openuniverse2024_roman_simulated_wideareasurvey.md
  tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md
Labels: html rendering
