Repository Caltech-IPAC/irsa-tutorials, pull requests merged in 2025-07, with the labels that each got.

#113 ENH: adding the spherex notebook
  index.md
  tutorials/spherex/spherex_intro.md
Labels: content

#116 Enable nb_scroll_outputs from latest myst-nb
  conf.py
  site_requirements.txt
Labels: infrastructure

#120 CI: adding SP proxy domain into redirect action
  .github/workflows/circleci-artifacts-redirector.yml
Labels: infrastructure

#121 ENH: adding irsa favicon
  _static/irsa-favicon.ico
  conf.py
Labels: infrastructure, html rendering / skip testing
