Repository Caltech-IPAC/irsa-tutorials, pull requests merged in 2025-09, with the labels that each got.

#137 Update Euclid spectra calls for new SpectrumDM service
  tutorials/cloud_access/euclid-cloud-access.md
  tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
  tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: content, GHA buildhtml

#139 MAINT: enlarge timeout for cosmodc2 notebook
  tutorials/cosmodc2/cosmoDC2_TAP_access.md
Labels: maintainance, infrastructure, html rendering / skip testing

#119 ENH: switching to JB2 infrastructure
  .circleci/config.yml
  .github/workflows/ci_publish.yml
  .github/workflows/ci_tests_run_notebooks.yml
  ignore_osx_testing
  ignore_tutorials/ignore_all_testing
  ignore_tutorials/ignore_circleci_testing
  ignore_tutorials/ignore_gha_testing
  ignore_tutorials/ignore_osx_testing
  ignore_tutorials/ignore_rendering
  ignore_tutorials/ignore_windows_testing
  ignore_windows_testing
  index.md
  myst.yml
  site_requirements.txt
  toc.yml
  tox.ini
  tutorials/parquet-catalog-demos/neowise-source-table-lightcurves.md
  tutorials/parquet-catalog-demos/neowise-source-table-strategies.md
Labels: html rendering / skip testing, GHA buildhtml
