Repository Caltech-IPAC/irsa-tutorials, pull requests merged in 2025-05, with the labels that each got.

#101 DOC: adding note about having recent enough versions
  .gitignore
  tutorials/cloud_access/euclid-cloud-access.md
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
  tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
  tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
  tutorials/euclid_access/Euclid_ERO.md
Labels: documentation, content, html rendering / skip testing

#102 DOC: adding myst markdown to the readme
  README.md
Labels: documentation

#103 MAINT: ray now has a py3.13 compatible release
  .binder/requirements.txt
  tox.ini
Labels: maintainance, infrastructure, force_run:all_tests

#104 Euclid MER catalog CMD: Reverse y-axis and zoom in
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
Labels: content, maintainance
