Repository Caltech-IPAC/irsa-tutorials, pull requests merged in 2025-03, with the labels that each got.

#37 IRSA-6436 Add NEOWISE year11 and addendum
  tutorials/parquet-catalog-demos/neowise-source-table-lightcurves.md
  tutorials/parquet-catalog-demos/neowise-source-table-strategies.md
Labels: content

#49 ENH: Euclid notebooks
  ignore_gha_testing
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
  tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: content, html rendering / skip testing

#53 CI: fix skip label CI skip and ignore all euclid testing for now
  .github/workflows/ci_tests_run_notebooks.yml
  conf.py
  ignore_gha_testing
Labels: bug, infrastructure, html rendering / skip testing

#50 Add a Euclid cloud access notebook
  tutorials/cloud_access/euclid-cloud-access.md
Labels: content, html rendering / skip testing

#55 ENH: adding Euclid ERO notebook
  .binder/requirements.txt
  conf.py
  index.md
  tutorials/euclid_access/Euclid_ERO.md
Labels: content, html rendering / skip testing

#57 Updating tutorials with new astroquery features
  .binder/requirements.txt
  tutorials/cloud_access/euclid-cloud-access.md
  tutorials/euclid_access/Euclid_ERO.md
Labels: maintainance, html rendering / skip testing

#52 Euclid rendering
  .binder/requirements.txt
  conf.py
  index.md
  tutorials/cloud_access/euclid-cloud-access.md
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
  tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: html rendering / skip testing

#66 CI: add all the versions for the oldestjob
  .binder/requirements.txt
  .github/workflows/ci_tests_run_notebooks.yml
  tox.ini
Labels: maintainance, infrastructure

#61 CI: Adding notebooks to the CI
  ignore_gha_testing
  tutorials/euclid_access/Euclid_ERO.md
Labels: infrastructure

#72 Updates to euclid notebook5
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: content

#74 CI: test only diffed notebooks
  tox.ini
  tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
Labels: infrastructure

#71 A bit extra markdown in the second notebook
  .binder/requirements.txt
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
Labels: content

#59 Adding Euclid notebook4
  index.md
  tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
Labels: content

#80 CI: fixing test status when no notebooks were collected for testing
  test_requirements.txt
  tox.ini
Labels: infrastructure

#78 Euclid notebooks: refactor the MER download and plot parts
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: content

#83 DOC: updating Euclid intros and titles
  tutorials/cloud_access/euclid-cloud-access.md
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
  tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
  tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: html rendering / skip testing

#84 MAINT: fix pip install lines
  tutorials/cloud_access/cloud-access-intro.md
  tutorials/cloud_access/euclid-cloud-access.md
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
  tutorials/euclid_access/Euclid_ERO.md
  tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md
Labels: maintainance, infrastructure, html rendering / skip testing

#87 CI: add back euclid tutorials to testing
  conf.py
  ignore_gha_testing
  tox.ini
Labels: maintainance, force_run:all_tests

#60 ENH: Euclid swap pyvo for astroquery
  tutorials/euclid_access/1_Euclid_intro_MER_images.md
  tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
  tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
  tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
Labels: enhancement, content
