Repository Caltech-IPAC/irsa-tutorials, pull requests merged in 2025-10, with the labels that each got.

#148 CI: making sure we fail buildhtml job with tracebacks
  tox.ini
Labels: infrastructure

#136 IRSA-7104: Add "Access IRSA HATS using lsdb" notebook
  .binder/requirements.txt
  index.md
  toc.yml
  tox.ini
  tutorials/parquet-catalog-demos/irsa-hats-with-lsdb.md
Labels: content

#151 Update lsdb version and remove universal_pathlib in requirements.txt
  .binder/requirements.txt
  tutorials/parquet-catalog-demos/irsa-hats-with-lsdb.md
Labels: bug, infrastructure, GHA buildhtml
